source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.2.0'

gem 'rails', '~> 7.0.0'
# SQLite for local development only
gem 'sqlite3', '~> 1.4', group: [:development, :test]
# PostgreSQL for production (Supabase / Render)
gem 'pg', '~> 1.1', group: :production
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem 'web-console'
end

# Windows does not include a zoneinfo database, so the tzinfo-data gem is required.
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bcrypt", "~> 3.1"

gem "image_processing", "~> 1.14"

gem "faraday", "~> 2.14"

gem "aws-sdk-s3", "~> 1.219"
gem "dotenv-rails", "~> 3.2"
